services:
  
  coding-task-backend:
    container_name: coding-task-backend
    restart: always
    volumes:
      - '/var/log/coding-task-backend:/app/log'
    environment:
      - TZ=Asia/Tbilisi
      - ASPNETCORE_ENVIRONMENT=Production
      - VIRTUAL_HOST=coding-task-backend.farhadmammadli.com
      - VIRTUAL_PORT=8080
    hostname: coding-task-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1gb
    build:
      context: .
      dockerfile: CodingTask.Host/Dockerfile
    image: coding-task-backend

  coding-task-ui:
    container_name: coding-task-ui
    restart: always
    environment:
      - TZ=Asia/Tbilisi
      - VIRTUAL_HOST=coding-task-ui.farhadmammadli.com
      - VIRTUAL_PORT=80
    hostname: coding-task-ui
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: 4gb
    build:
      context: ./CodingTask.UI
      dockerfile: CodingTask.UI/Dockerfile
    image: coding-task-ui

networks:
  default:
    external: true
    name: nat  